name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      imageName:
        type: string
        default: ${{ github.repository }}
        description: "The name for the docker image (Default: Repository name)"
      imageTag:
        type: string
        required: true
        description: "The tag for the docker image (usually a version tag without leading 'v')"
      dockerFile:
        type: string
        default: Dockerfile
        description: "The path to the Dockerfile (Default: ./Dockerfile)"
      dockerContext:
        type: string
        default: .
        description: "The context for the Docker build (Default: .)"
      buildArgs:
        type: string
        description: "List of additional build contexts (e.g., name=path)"
        required: false
      
    secrets:
      registryUser:
        required: true
      registryPassword:
        required: true


jobs:
  build:
    name: Build Docker Image for ${{ inputs.imageTag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.registryUser }}
          password: ${{ secrets.registryPassword }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dockerContext }}
          file: ${{ inputs.dockerFile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ inputs.imageName }}:${{ inputs.imageTag }}"
          build-args: ${{ inputs.buildArgs }}