name: Deploy a file to the VM

on:
  workflow_call:
    inputs:
      VM_HOST:
        type: string
        required: true
        description: "The host address of the VM"
      VM_USERNAME:
        type: string
        required: true
        description: "The user name when connecting to the VM"
      SOURCE_FILES:
        type: string
        required: true
        description: "The list of file to copy to the VM (e.g. \"tests/a.txt,tests/b.txt\")"
      DST_FOLDER:
        type: string
        required: true
        description: "The destination folder on the VM (must be a directory)"
      
    secrets:
      VM_SSH_PRIVATE_KEY:
        required: true      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy file to VM Host
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.VM_HOST }}
        username: ${{ inputs.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        # Defined in the Org
        proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
        proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
        proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
        proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
        #####################
        source: ${{ inputs.SOURCE_FILES }}
        target: ${{ inputs.DST_FOLDER }}