name: Docker Compose Down on a VM

on:
  workflow_call:
    inputs:
      VM_HOST:
        type: string
        required: true
        description: "The host address of the VM"
      VM_USERNAME:
        type: string
        required: true
        description: "The user name when connecting to the VM"
      DIRECTORY:
        type: string
        required: false
        default: .
        description: "The directory to execute the command in (Default: .)"
      COMPOSE_FILE:
        type: string
        required: false
        default: docker-compose.yml
        description: "The file used to execute the command (Default: )"
      ENV_FILE:
        type: string
        required: false
        description: "The optional .env file to source"
      
    secrets:
      VM_SSH_PRIVATE_KEY:
        required: true      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VM and Execute Docker-Compose Down
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.VM_HOST }}
          username: ${{ inputs.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.DEPLOYMENT_GATEWAY_HOST }}
          proxy_username: ${{ vars.DEPLOYMENT_GATEWAY_USER }}
          proxy_key: ${{ secrets.DEPLOYMENT_GATEWAY_SSH_KEY }}
          proxy_port: ${{ vars.DEPLOYMENT_GATEWAY_PORT }}
          script: |
            cd ${{ inputs.DIRECTORY }}
            if [ -n "${{ inputs.ENV_FILE }}" ]; then
              docker compose -f ${{ inputs.COMPOSE_FILE }} --env-file ${{ inputs.ENV_FILE }} down --remove-orphans --rmi all
            else
              docker compose -f ${{ inputs.COMPOSE_FILE }} down --remove-orphans --rmi all
            fi