on: workflow_dispatch

jobs:
  deploy-prod-container:
    uses: ./.github/workflows/deploy-docker-compose.yml
    secrets: inherit
    with:
      environment: production
      main-image-name: "image"
      image-tag: "latest"
      env-vars: |
        ANOTHER_VARIABLE=VALUE
        KEY=KEY_VALUE
