on: workflow_dispatch

jobs:
  deploy-prod-container:
    uses: ./.github/workflows/deploy-docker-compose.yml
    secrets:
      env-vars: ${{secrets.ENV_VARIABLES}}
    with:
      environment: production
      main-image-name: "image"
      image-tag: "latest"
